version: '3.8'
services:
  server:
    build:
      context: .
    tty: true
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: product_managment
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_ROOT_HOST: '%'
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    expose:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - db-data:/var/lib/mysql
volumes:
  db-data:
networks:
  app-network:
    driver: bridge
