version: '3.8'
services:
  server:
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: product_managment
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - db-data:/var/lib/mysql
volumes:
  db-data:
networks:
  app-network:
    driver: bridge
